# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Despell < Formula
  desc "despell puts icons in tmux's statusline"
  homepage "https://github.com/bensadeh/despell/"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bensadeh/despell/releases/download/0.6.1/despell_0.6.1_macOS_arm64.tar.gz"
      sha256 "27b2384f75294bcf128cd741672c84bb358c2c7f0cbd32301d24796522139b5e"

      def install
        bin.install "despell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/despell/releases/download/0.6.1/despell_0.6.1_macOS_64-bit.tar.gz"
      sha256 "f09381614e58be2d21c66ab0711ab8bddaa9a9e801232416a68ef1bc30243cf4"

      def install
        bin.install "despell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bensadeh/despell/releases/download/0.6.1/despell_0.6.1_Linux_arm64.tar.gz"
      sha256 "0bfae4ca6919abef51856491753e1df318835c8d1ba80decaef4d4a587fbc858"

      def install
        bin.install "despell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/despell/releases/download/0.6.1/despell_0.6.1_Linux_64-bit.tar.gz"
      sha256 "10b932fc47228be5b85eaabec5df459d0ccd91a23a9356605877c661037faa1f"

      def install
        bin.install "despell"
      end
    end
  end
end
