# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Despell < Formula
  desc "despell puts icons in tmux's statusline"
  homepage "https://github.com/bensadeh/despell/"
  version "0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/despell/releases/download/0.8/despell_0.8_macOS_64-bit.tar.gz"
      sha256 "075136da814da590c9ceff550e4effe29e938bc45b89bce93d3ab0d484c7f354"

      def install
        man1.install "#{buildpath}/share/man/abc.1"
        bin.install "despell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bensadeh/despell/releases/download/0.8/despell_0.8_macOS_arm64.tar.gz"
      sha256 "fc9f25d090ae5091372c949797a74c19aedef76afdf52120c479aa99aa662d12"

      def install
        man1.install "#{buildpath}/share/man/abc.1"
        bin.install "despell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bensadeh/despell/releases/download/0.8/despell_0.8_Linux_arm64.tar.gz"
      sha256 "0e9c875f0db4fcd4fbebf42438e396f5abf99973f2668091fa997e24b8e3f04c"

      def install
        man1.install "#{buildpath}/share/man/abc.1"
        bin.install "despell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bensadeh/despell/releases/download/0.8/despell_0.8_Linux_64-bit.tar.gz"
      sha256 "384e89e233b91065cc9c3665be7f4d8a7f39d0fe630aafe269fd0a4f28633775"

      def install
        man1.install "#{buildpath}/share/man/abc.1"
        bin.install "despell"
      end
    end
  end
end
