# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magica < Formula
  desc "magica is a tool for showing icons in tmux's statusline"
  homepage "https://github.com/bensadeh/magica/"
  version "0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bensadeh/magica/releases/download/0.1/magica_0.1_macOS_64-bit.tar.gz"
    sha256 "f71629b2df186830d766a3f8dc30b77e9aab3bd3631919556c4962c4cd3ba325"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bensadeh/magica/releases/download/0.1/magica_0.1_macOS_arm64.tar.gz"
    sha256 "6a8171936ae7e287803d80be8235c0312f350273fcdc9a426df1cdb3cdf2af73"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bensadeh/magica/releases/download/0.1/magica_0.1_Linux_64-bit.tar.gz"
    sha256 "7243da70138d86287a86b49b6e8a54737c05f6ee54bf48f4874715ff76f1f33c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bensadeh/magica/releases/download/0.1/magica_0.1_Linux_arm64.tar.gz"
    sha256 "f97a94e27a9309398d31c264a89d41a018828fc8ecd2faa786c128bb50d17c82"
  end

  def install
    bin.install "magica" => "despell"
  end
end
